### ISSUE TITLE
Unable to Launch A New Survey - Error "Unknown column 'survey_id' in 'field list' 

### ISSUE THREAD

**Issue by blujeep** [Clark-College-CTEC/team2-final-project#13]
Bug: Clicking Start Survey Button in post_survey.php returns the error "Unknown column 'survey_id' in 'field list'.

STEPS: 
1) Log-in as Instructor
2) Click "Launch A Survey" link from the Dashboard.
3) In post_survey.php select a survey name from the Survey drop down.
4) Select a team from the Team list
5) Enter a Start and End date and time (5/28/2017 12:00 PM and 5/29/2017 12:00 PM).
6) Click Start Survey button.

RESULT: User is returned to the Dashboard and the error Unknown column 'survey_id' in 'field list' is displayed with orange/red background above the My Surveys list.

The survey is listed twice in the Dashboard My Survey list with blank Start/End date.

In the database table  tbl_survey, the survey is now listed twice with NULL instance_id and has two different survey_id values.

tbl_survey_instance table does not list the new survey.

EXPECTED:: Clicking Start Survey to create a new Survey instance with an unique survey_id a non-NULL value in tbl_survey table and  the tbl_survey_instance table.

Additionally need to provide a way for the Instructor to change the name of the survey instance. For example Survey
![unknownsurvey_iderror](https://cloud.githubusercontent.com/assets/18266253/26558491/0e0f1ac4-445e-11e7-9e56-03cdcd57f724.jpg)
-fall, Survey-spring. Currently only thing distinguishing them in the Instructor's My Surveys list is the Start/End date.
![launchsurvey_dbresults](https://cloud.githubusercontent.com/assets/18266253/26558433/931e805c-445d-11e7-8e9c-7c7d30feca7f.jpg)
![unknownsurvey_iderror](https://cloud.githubusercontent.com/assets/18266253/26558432/931e15ae-445d-11e7-8a98-ed01fd5f0479.jpg)

**Comment by robin5** [comment]
Fixed #13 in commit 903740180d3d5d8d3c5cbbeb1f17a1c97b836e92 Will create a separate enhancement request to be able to rename a launched instance of a survey.
