### ISSUE TITLE
Graphic charts in survey results are or in font of header

### ISSUE THREAD

**Issue by blujeep** [Clark-College-CTEC/team2-final-project#52]
The grade/percentage pie chart scrolls over the header on survey_results.php page
Steps:
1. Log in as instructor
2. click on view results for a survey in the dashboard
3. scroll to the bottom of the page

Result:
![snip_20170613102105](https://user-images.githubusercontent.com/18266253/27095313-0e59eb6a-5022-11e7-96dd-5e186a87c2ca.png)

**Comment by kingdr360** [comment]
Within css added z-index: 1; to the .fixedheader css.  Now the charts go behind the header.

**Comment by kingdr360** [comment]
![survey](https://user-images.githubusercontent.com/22796517/27107930-8f55aab0-504f-11e7-9229-ee425705932b.JPG)
