### ISSUE TITLE
question input area too small

### ISSUE THREAD

**Issue by blujeep** [Clark-College-CTEC/team2-final-project#66]
UI Bug:
The textarea input for add question in edit_survey.php is smaller than expected when viewed at full screen. It should fill the entire cell. There are gaps on left and right side.
Steps: 
1. Log in as instructor
2. Click Create Survey
3. Expand window to fill screen.

Result:
![questiontxtarea](https://user-images.githubusercontent.com/18266253/27246383-10eae68c-52a6-11e7-9571-a55e8582d658.JPG)

**Comment by kingdr360** [comment]
Fixed
