### ISSUE TITLE
Error Creating Survey if a question is deleted

### ISSUE THREAD

**Issue by blujeep** [Clark-College-CTEC/team2-final-project#68]
The first time a survey is create, deleting a question can cause an error when the survey is saved.
1. log on as and instructor and click Create a survey template
2. Add 3 questions and put text in each textarea
3. Delete question 2.
4. Click add question and enter text for all questions.
5. Click Save&Exit.
Result: Followng error is displayed 
Notice: Undefined offset: 1 in C:\xampp\htdocs\team2-final-project\includes\Database\SurveyFactory.php on line 130

The survey is saved. If edited there is one blank question

**Comment by robin5** [comment]
Fixed in commit #8d8a19f
