### ISSUE TITLE
Tone on Surveys's not done causes undefined index

### ISSUE THREAD

**Issue by robin5** [Clark-College-CTEC/team2-final-project#7]
When Refresh is pressed on the summary tone for a survey question that has not yet been filled out by a student, the following error message is displayed: **Notice: Undefined index: document_tone in C:\xampp\htdocs\ctec227\team2-final-project\includes\ToneAnalyzer\tone.inc.php on line 51**

**Comment by blujeep** [comment]
Should be fixed now in the last post of the tone files on 5/28

**Comment by robin5** [comment]
Fixed.
