### ISSUE TITLE
Summary tone displays into div of the first question

### ISSUE THREAD

**Issue by robin5** [Clark-College-CTEC/team2-final-project#8]
When you press refresh, and the summary tone displays itself, it should display within the div of the summary button.  It however displays into the div of the question just below it.

**Comment by robin5** [comment]
[sample1.docx](https://github.com/Clark-College-CTEC/team2-final-project/files/1034881/sample1.docx)

**Comment by blujeep** [comment]
Should be fixed in 2nd and latest post of the CSS on 5/28 . Added margin to the #tone-summary, #txt-summary divs to prevent overlap. You can tell you have new CSS if log in name in header is all caps.
